name: Browser_build
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - chrome
          - electron

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Cypress run
        run: npm run test:loginTest:${{ matrix.browser }} # Adjust the command based on your project setup

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report 
          path: cypress/reports/html
      